/*-------------------------------------------------------------
// Description:
Dao = Data access object.
Interface that defines how the Exercise database in AppDatabase can be accessed.
The function implementations are generated by Room with the annotation settings.
(https://developer.android.com/training/data-storage/room/accessing-data.html)
-------------------------------------------------------------*/
package com.romanbrunner.apps.fitnesstracker.database;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;

import java.util.List;


@Dao
public interface ExerciseInfoDao
{
    // --------------------
    // Functional code
    // --------------------

    @Query("SELECT * FROM exerciseInfo")
    LiveData<List<ExerciseInfoEntity>> loadAll();

    @Query("SELECT * FROM exerciseInfo WHERE name LIKE :searchName AND token LIKE :searchToken LIMIT 1")
    LiveData<ExerciseInfoEntity> loadByNameAndToken(String searchName, String searchToken);

    @Insert
    void insert(List<ExerciseInfoEntity> exerciseInfoList);

    @Update
    void update(List<ExerciseInfoEntity> exerciseInfoList);
}