/*-------------------------------------------------------------
// Description:
Dao = Data access object.
Interface that defines how the Exercise database in AppDatabase can be accessed.
The function implementations are generated by Room with the annotation settings.
(https://developer.android.com/training/data-storage/room/accessing-data.html)
-------------------------------------------------------------*/
package com.romanbrunner.apps.fitnesstracker.database;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;

import java.util.Date;
import java.util.List;


@Dao
public interface ExerciseSetDao
{
    // --------------------
    // Functional code
    // --------------------

    @Query("SELECT * FROM exerciseSets")
    LiveData<List<ExerciseSetEntity>> loadAll();

    @Query("SELECT * FROM exerciseSets WHERE workoutUnitDate = :searchWorkoutUnitDate")
    LiveData<List<ExerciseSetEntity>> loadByWorkoutUnitDate(Date searchWorkoutUnitDate);

    @Query("SELECT * FROM exerciseSets WHERE exerciseInfoName = :exerciseInfoName AND workoutUnitDate = (SELECT MAX(es2.workoutUnitDate) FROM exerciseSets es2 WHERE es2.exerciseInfoName = :exerciseInfoName)")
    LiveData<List<ExerciseSetEntity>> loadNewestByExerciseInfoName(String exerciseInfoName);

    @Query("DELETE FROM exerciseSets WHERE exerciseInfoName = :exerciseInfoName")
    void deleteByExerciseInfoName(String exerciseInfoName);

    @Insert
    void insert(List<ExerciseSetEntity> exercises);

    @Update
    void update(List<ExerciseSetEntity> exercises);
}