/*-------------------------------------------------------------
// Description:
Dao = Data access object.
Interface that defines how the Exercise database in AppDatabase can be accessed.
The function implementations are generated by Room with the annotation settings.
(https://developer.android.com/training/data-storage/room/accessing-data.html)
-------------------------------------------------------------*/
package com.romanbrunner.apps.fitnesstracker.database;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Insert;
import androidx.room.OnConflictStrategy;
import androidx.room.Query;
import androidx.room.Update;

import java.util.List;
import java.util.Set;


@Dao
public interface ExerciseInfoDao
{
    // --------------------
    // Functional code
    // --------------------

    @Query("SELECT * FROM exerciseInfo")
    LiveData<List<ExerciseInfoEntity>> loadAll();

    @Query("SELECT * FROM exerciseInfo WHERE name IN (:searchNames)")
    LiveData<List<ExerciseInfoEntity>> loadByNames(Set<String> searchNames);

    @Query("DELETE FROM exerciseInfo WHERE name = :name")
    void deleteByName(String name);

    @Insert
    void insert(List<ExerciseInfoEntity> exerciseInfoList);

    @Insert(onConflict = OnConflictStrategy.IGNORE)
    Long insertIgnore(ExerciseInfoEntity exerciseInfo);

    @Update
    void update(ExerciseInfoEntity... exerciseInfo);
}