/*-------------------------------------------------------------
// Description:
Dao = Data access object.
Interface that defines how the Workout database in AppDatabase can be accessed.
The function implementations are generated by Room with the annotation settings.
(https://developer.android.com/training/data-storage/room/accessing-data.html)
-------------------------------------------------------------*/
package com.romanbrunner.apps.fitnesstracker.database;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;

import com.romanbrunner.apps.fitnesstracker.ui.MainActivity;

import java.util.List;


@Dao
public interface WorkoutUnitDao
{
    // --------------------
    // Functional code
    // --------------------

    @Query("SELECT * FROM WorkoutUnits WHERE id < " + MainActivity.DEBUG_WORKOUT_MIN_ID + " ORDER BY id DESC LIMIT 1")
    LiveData<WorkoutUnitEntity> loadNewestNormal();

    @Query("SELECT * FROM WorkoutUnits WHERE id >= " + MainActivity.DEBUG_WORKOUT_MIN_ID + " ORDER BY id DESC LIMIT 1")
    LiveData<WorkoutUnitEntity> loadNewestDebug();

    @Query("SELECT * FROM WorkoutUnits WHERE studio = :searchStudio AND id < " + MainActivity.DEBUG_WORKOUT_MIN_ID + " ORDER BY id DESC LIMIT 1")
    LiveData<WorkoutUnitEntity> loadNewestByStudioNormal(String searchStudio);

    @Query("SELECT * FROM WorkoutUnits WHERE studio = :searchStudio AND id >= " + MainActivity.DEBUG_WORKOUT_MIN_ID + " ORDER BY id DESC LIMIT 1")
    LiveData<WorkoutUnitEntity> loadNewestByStudioDebug(String searchStudio);

    @Query("SELECT * FROM WorkoutUnits WHERE studio = :searchStudio AND name = :searchName AND id < " + MainActivity.DEBUG_WORKOUT_MIN_ID + " ORDER BY id DESC LIMIT 1")
    LiveData<WorkoutUnitEntity> loadNewestByStudioAndNameNormal(String searchStudio, String searchName);

    @Query("SELECT * FROM WorkoutUnits WHERE studio = :searchStudio AND name = :searchName AND id >= " + MainActivity.DEBUG_WORKOUT_MIN_ID + " ORDER BY id DESC LIMIT 1")
    LiveData<WorkoutUnitEntity> loadNewestByStudioAndNameDebug(String searchStudio, String searchName);

    @Query("SELECT * FROM WorkoutUnits WHERE id < " + MainActivity.DEBUG_WORKOUT_MIN_ID + " AND id < (SELECT MAX(id) FROM WorkoutUnits WHERE id < " + MainActivity.DEBUG_WORKOUT_MIN_ID + ") ORDER BY id DESC LIMIT 1")
    LiveData<WorkoutUnitEntity> loadLastNormal();

    @Query("SELECT * FROM WorkoutUnits WHERE id >= " + MainActivity.DEBUG_WORKOUT_MIN_ID + " AND id < (SELECT MAX(id) FROM WorkoutUnits WHERE id >= " + MainActivity.DEBUG_WORKOUT_MIN_ID + ") ORDER BY id DESC LIMIT 1")
    LiveData<WorkoutUnitEntity> loadLastDebug();

    @Query("SELECT * FROM WorkoutUnits WHERE studio = :searchStudio AND id < " + MainActivity.DEBUG_WORKOUT_MIN_ID)
    LiveData<List<WorkoutUnitEntity>> loadAllByStudioNormal(String searchStudio);

    @Query("SELECT * FROM WorkoutUnits WHERE studio = :searchStudio AND id >= " + MainActivity.DEBUG_WORKOUT_MIN_ID)
    LiveData<List<WorkoutUnitEntity>> loadAllByStudioDebug(String searchStudio);

    @Query("SELECT * FROM WorkoutUnits WHERE studio = :searchStudio AND name = :searchName AND id < " + MainActivity.DEBUG_WORKOUT_MIN_ID)
    LiveData<List<WorkoutUnitEntity>> loadAllByStudioAndNameNormal(String searchStudio, String searchName);

    @Query("SELECT * FROM WorkoutUnits WHERE studio = :searchStudio AND name = :searchName AND id >= " + MainActivity.DEBUG_WORKOUT_MIN_ID)
    LiveData<List<WorkoutUnitEntity>> loadAllByStudioAndNameDebug(String searchStudio, String searchName);

    @Query("SELECT * FROM WorkoutUnits WHERE id < " + MainActivity.DEBUG_WORKOUT_MIN_ID)
    LiveData<List<WorkoutUnitEntity>> loadAllNormal();

    @Query("SELECT * FROM WorkoutUnits WHERE id >= " + MainActivity.DEBUG_WORKOUT_MIN_ID)
    LiveData<List<WorkoutUnitEntity>> loadAllDebug();

    @Insert
    void insert(WorkoutUnitEntity... workoutUnits);

    @Update
    void update(WorkoutUnitEntity... workoutUnits);

    @Delete
    void delete(WorkoutUnitEntity... workoutUnit);
    @Delete
    void delete(List<WorkoutUnitEntity> workoutUnits);
}