/*-------------------------------------------------------------
// Description:
Dao = Data access object.
Interface that defines how the Workout database in AppDatabase can be accessed.
The function implementations are generated by Room with the annotation settings.
(https://developer.android.com/training/data-storage/room/accessing-data.html)
-------------------------------------------------------------*/
package com.romanbrunner.apps.fitnesstracker.database;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Insert;
import androidx.room.OnConflictStrategy;
import androidx.room.Query;
import androidx.room.Update;

import java.util.List;


@Dao
public interface WorkoutInfoDao
{
    // --------------------
    // Functional code
    // --------------------

    @Query("SELECT * FROM WorkoutInfo WHERE name = :searchName AND version = :searchVersion")
    LiveData<WorkoutInfoEntity> loadByNameAndVersion(String searchName, int searchVersion);

    @Insert
    void insert(List<WorkoutInfoEntity> workoutInfo);

    @Insert(onConflict = OnConflictStrategy.IGNORE)
    Long insertIgnore(WorkoutInfoEntity workoutInfo);

    @Update
    void update(WorkoutInfoEntity... workoutInfo);
}