/*-------------------------------------------------------------
// Description:
Dao = Data access object.
Interface that defines how the Workout database in AppDatabase can be accessed.
The function implementations are generated by Room with the annotation settings.
(https://developer.android.com/training/data-storage/room/accessing-data.html)
-------------------------------------------------------------*/
package com.romanbrunner.apps.fitnesstracker.database;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;

import com.romanbrunner.apps.fitnesstracker.ui.MainActivity;

import java.util.List;


@Dao
public interface WorkoutDao
{
    // --------------------
    // Functional code
    // --------------------

    @Query("SELECT * FROM workouts WHERE id < " + MainActivity.DEBUG_WORKOUT_MIN_ID)
    LiveData<List<WorkoutEntity>> loadAll();

    @Query("SELECT * FROM workouts WHERE id >= " + MainActivity.DEBUG_WORKOUT_MIN_ID)
    LiveData<List<WorkoutEntity>> loadAllDebug();

    @Query("SELECT * FROM workouts WHERE id < " + MainActivity.DEBUG_WORKOUT_MIN_ID + " ORDER BY id DESC LIMIT 1")
    LiveData<WorkoutEntity> loadNewest();

    @Query("SELECT * FROM workouts WHERE id >= " + MainActivity.DEBUG_WORKOUT_MIN_ID + " ORDER BY id DESC LIMIT 1")
    LiveData<WorkoutEntity> loadNewestDebug();

    @Query("SELECT * FROM workouts WHERE id < " + MainActivity.DEBUG_WORKOUT_MIN_ID + " AND id < (SELECT MAX(id) FROM workouts) ORDER BY id DESC LIMIT 1")
    LiveData<WorkoutEntity> loadLast();

    @Query("SELECT * FROM workouts WHERE id >= " + MainActivity.DEBUG_WORKOUT_MIN_ID + " AND id < (SELECT MAX(id) FROM workouts) ORDER BY id DESC LIMIT 1")
    LiveData<WorkoutEntity> loadLastDebug();

    @Insert
    void insert(WorkoutEntity... workouts);

    @Update
    void update(WorkoutEntity... workouts);

    @Delete
    void delete(WorkoutEntity... workouts);
}