/*-------------------------------------------------------------
// Description:
Dao = Data access object.
Interface that defines how the Workout database in AppDatabase can be accessed.
The function implementations are generated by Room with the annotation settings.
(https://developer.android.com/training/data-storage/room/accessing-data.html)
-------------------------------------------------------------*/
package com.romanbrunner.apps.fitnesstracker.database;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Insert;
import androidx.room.OnConflictStrategy;
import androidx.room.Query;
import androidx.room.Update;

import java.util.List;


@Dao
public interface WorkoutInfoDao
{
    // --------------------
    // Functional code
    // --------------------

    @Query("SELECT * FROM WorkoutInfo WHERE studio = :searchStudio AND name = :searchName AND version = :searchVersion")
    LiveData<WorkoutInfoEntity> loadByStudioAndNameAndVersion(String searchStudio, String searchName, int searchVersion);

    @Query("SELECT * FROM WorkoutInfo WHERE studio = :searchStudio")
    LiveData<List<WorkoutInfoEntity>> loadByStudio(String searchStudio);

    @Query("SELECT * FROM WorkoutInfo WHERE studio = :searchStudio AND name = :searchName ORDER BY version DESC LIMIT 1")
    LiveData<WorkoutInfoEntity> loadNewestByStudioAndName(String searchStudio, String searchName);

    @Query("SELECT * FROM WorkoutInfo WHERE studio = :searchStudio ORDER BY name ASC, version DESC LIMIT 1")
    LiveData<WorkoutInfoEntity> loadFirstByStudio(String searchStudio);

    @Query("SELECT * FROM WorkoutInfo")
    LiveData<List<WorkoutInfoEntity>> loadAll();

    @Insert
    void insert(List<WorkoutInfoEntity> workoutInfo);

    @Insert(onConflict = OnConflictStrategy.IGNORE)
    Long insertIgnore(WorkoutInfoEntity workoutInfo);

    @Update
    void update(WorkoutInfoEntity... workoutInfo);

    @Query("DELETE FROM WorkoutInfo WHERE studio = :searchStudio AND name = :searchName AND version > :searchVersion")
    void deleteNewerVersions(String searchStudio, String searchName, int searchVersion);
}