/*-------------------------------------------------------------
// Description:
Dao = Data access object.
Interface that defines how the Workout database in AppDatabase can be accessed.
The function implementations are generated by Room with the annotation settings.
(https://developer.android.com/training/data-storage/room/accessing-data.html)
-------------------------------------------------------------*/
package com.romanbrunner.apps.fitnesstracker.database;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.OnConflictStrategy;
import androidx.room.Query;
import androidx.room.Update;

import java.util.List;


@Dao
public interface WorkoutDao
{
    // --------------------
    // Functional code
    // --------------------

    @Query("SELECT * FROM workouts")
    LiveData<List<WorkoutEntity>> loadAll();

    @Query("SELECT * FROM workouts ORDER BY date DESC LIMIT 1")
    LiveData<WorkoutEntity> loadLatest();

    @Query("SELECT * FROM workouts WHERE id LIKE :searchId LIMIT 1")
    LiveData<WorkoutEntity> loadById(int searchId);

    @Query("SELECT * FROM workouts WHERE id IN (:searchIds)")
    LiveData<List<WorkoutEntity>> loadByIds(int[] searchIds);

    @Insert
    void insert(WorkoutEntity... workouts);

    @Insert
    void insert(List<WorkoutEntity> workouts);

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    void insertOrReplace(WorkoutEntity... workouts);

    @Update
    void update(WorkoutEntity... workouts);

    @Update
    void update(List<WorkoutEntity> workouts);

    @Delete
    void delete(WorkoutEntity... workouts);
}